scene:
  ANIMATED_CHARACTERS:
    - character_cfg: ./output/char_cfg.yaml
      motion_cfg: ./config/motion/jumping_jacks.yaml
      retarget_cfg: ./config/retarget/cmu1_pfp.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./vedio.gif
view:
  USE_MESA: True
