scene:
  ANIMATED_CHARACTERS:
    - character_cfg: /home/ajay/Animations/AnimatedDrawings/examples/characters/char1/char_cfg.yaml
      motion_cfg: examples/config/motion/jumping.yaml
      retarget_cfg: /home/ajay/Animations/AnimatedDrawings/newretarget_0.yaml
    - character_cfg: /home/ajay/Animations/AnimatedDrawings/examples/characters/char1/char_cfg.yaml
      motion_cfg: /home/ajay/Animations/AnimatedDrawings/config/motion/jumping.yaml
      retarget_cfg: /home/ajay/Animations/AnimatedDrawings/newretarget_1.yaml

controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.gif

view:
  WINDOW_DIMENSIONS: [600, 600]
  USE_MESA: True


