filepath: ./examples/bvh/fair1/Jump.bvh
start_frame_idx: 0
end_frame_idx: 110
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +y
