filepath: examples/bvh/fair1/Running_Left_to_Right.bvh
start_frame_idx: 1
end_frame_idx: 110
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +y
