filepath: examples/bvh/fair1/Run.bvh
start_frame_idx: 1
end_frame_idx: 58
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z