filepath: examples/bvh/fair1/T-Rex_Running_Right_To_Left.bvh
start_frame_idx: 1
end_frame_idx: 42
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +y
